# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener: true
    body_listener:
        enabled: true
    body_converter:
        enabled: true
    view:
        view_response_listener:
            enabled: true
            force: true
    exception:
        enabled: true
